In [1]:
import numpy as np
import scipy as sc
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
a = np.array([1,2,0])
b = np.array([-3, 1.5, 1])
A = np.array([[1,0,0],[0,2,0],[1,0,1]])

print(a,b,'\n',A)

[1 2 0] [-3.   1.5  1. ] 
 [[1 0 0]
 [0 2 0]
 [1 0 1]]


In [3]:
print(A@a)

[1 4 1]


In [4]:
np.dot(a,b)

0.0

In [5]:
np.cross(a,b)

array([ 2. , -1. ,  7.5])

In [6]:
print(np.linalg.inv(A) @ a)

[ 1.  1. -1.]


In [7]:
def slow_matvec(matrix, vector):
    assert matrix.shape[1] == vector.shape[0]
    result = []
    for r in range(matrix.shape[0]):
        value = 0
        for c in range(matrix.shape[1]):
            value += matrix[r, c] * vector[c]
        result.append(value)
    return np.array(result)


# Example of using this function
matrix = np.random.rand(3, 3)
vector = np.random.rand(3)
print(slow_matvec(matrix, vector))
print(matrix @ vector)

[1.17784842 0.7155801  0.92083312]
[1.17784842 0.7155801  0.92083312]


In [8]:
def faster_matvec(matrix, vector):
    assert matrix.shape[1] == vector.shape[0]
    result = []
    for r in range(matrix.shape[0]):
        result.append(np.dot(matrix[r],vector))
    return np.array(result)


# Example of using this function
matrix = np.random.rand(3, 3)
vector = np.random.rand(3)
print(faster_matvec(matrix, vector))
print(matrix @ vector)

[0.91233012 0.64084424 0.79329963]
[0.91233012 0.64084424 0.79329963]


### Assert testing
When creating a function can use 'assert' to check the validity of the new function by asserting that it completes a specific job this is often done by comparison to a pre-written function which is available as we are trying to create optimisations of pre-written functions. If the function is incorrect an assertion error will occur.

Due to machine precision sometimes the '==' check  may fail so we may use np.isclose() instead, for vectors and matrices we can use np.allclose().

In [9]:
def add(a, b):
    return a + b


assert add(1, 1) == 2
assert add(4, 5) == 9

In [10]:
def faster_matvec(matrix, vector):
    assert matrix.shape[1] == vector.shape[0]
    result = []
    for r in range(matrix.shape[0]):
        value = np.dot(matrix[r],vector)
        result.append(value)
    return np.array(result)


# Example of using this function
matrix = np.random.rand(3, 3)
vector = np.random.rand(3)

assert np.allclose(faster_matvec(matrix, vector), matrix@vector)

### Timing

In [14]:
from timeit import timeit

n = 20

def f(n):
    num_its = 100
    matrix = np.random.rand(n, n)
    vector = np.random.rand(n)
    
    tf = timeit(lambda: faster_matvec(matrix, vector), number=num_its)
    tf_string = timeit('faster_matvec(matrix, vector)', setup = 'from __main__ import faster_matvec, matrix, vector'
                       ,number=num_its)
    ts = timeit(lambda: slow_matvec(matrix, vector), number=num_its)
    ts_string = timeit('slow_matvec(matrix, vector)', setup = 'from __main__ import slow_matvec, matrix, vector'
                       ,number=num_its)
    print(' Fast:', tf,' Fast string:', tf_string, '\n', 'Slow:', ts,' Slow string:', ts_string)
    
f(n)

#observation: slow matvec is fast for 2x2 matrices

 Fast: 0.012983077999706438  Fast string: 0.15696865300014906 
 Slow: 0.018701567999414692  Slow string: 9.816034865999427


### Plotting

In [12]:
n = [2,5,10,20,50,100,500]
y0 = np.zeros((len(n), 4))
num_its = 100

for i in range(len(n)):
    matrix = np.random.rand(n[i], n[i])
    vector = np.random.rand(n[i])
    
    tf = timeit(lambda: faster_matvec(matrix, vector), number=num_its)
    tf_string = timeit('faster_matvec(matrix, vector)', setup = 'from __main__ import faster_matvec, matrix, vector'
                       ,number=num_its)
    ts = timeit(lambda: slow_matvec(matrix, vector), number=num_its)
    ts_string = timeit('slow_matvec(matrix, vector)', setup = 'from __main__ import slow_matvec, matrix, vector'
                       ,number=num_its)
    
    y0[i] = np.array([tf, tf_string, ts, ts_string])

KeyboardInterrupt: 

In [ ]:
print(y0[:,0])

plt.figure(figsize=(14,7))
plt.plot(n, y0[:,0], label ='Fast')
plt.plot(n, y0[:,1], label ='Fast string')
plt.plot(n, y0[:,2], label ='Slow')
plt.plot(n, y0[:,3], label ='Slow string')

plt.xlabel("Matrix size")
plt.ylabel("Time")
plt.legend()
plt.xscale('log')
plt.yscale('log')

#plt.axis('equal')